//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flow.Launcher.Plugin.ShortcutPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flow.Launcher.Plugin.ShortcutPlugin.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while exporting shortcuts.
        /// </summary>
        internal static string Error_while_exporting_shortcuts {
            get {
                return ResourceManager.GetString("Error_while_exporting_shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export shortcuts.
        /// </summary>
        internal static string Export_shortcuts {
            get {
                return ResourceManager.GetString("Export_shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import shortcuts file.
        /// </summary>
        internal static string Failed_to_import_shortcuts_file {
            get {
                return ResourceManager.GetString("Failed_to_import_shortcuts_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import shortcuts.
        /// </summary>
        internal static string Import_shortcuts {
            get {
                return ResourceManager.GetString("Import_shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open plugin config.
        /// </summary>
        internal static string SettingsManager_OpenConfigCommand_Open_plugin_config {
            get {
                return ResourceManager.GetString("SettingsManager_OpenConfigCommand_Open_plugin_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open plugin helpers.
        /// </summary>
        internal static string SettingsManager_OpenHelpersCommand_Open_plugin_helpers {
            get {
                return ResourceManager.GetString("SettingsManager_OpenHelpersCommand_Open_plugin_helpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload plugin.
        /// </summary>
        internal static string SettingsManager_ReloadCommand_Reload_plugin {
            get {
                return ResourceManager.GetString("SettingsManager_ReloadCommand_Reload_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut type unsupported!.
        /// </summary>
        internal static string Shortcut_type_not_supported {
            get {
                return ResourceManager.GetString("Shortcut_type_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts file not found!.
        /// </summary>
        internal static string Shortcuts_file_not_found {
            get {
                return ResourceManager.GetString("Shortcuts_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string Shortcuts_Query_No_results_found {
            get {
                return ResourceManager.GetString("Shortcuts_Query_No_results_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} shortcut &apos;{1}&apos;.
        /// </summary>
        internal static string ShortcutsManager_AddShortcut_Add_shortcut {
            get {
                return ResourceManager.GetString("ShortcutsManager_AddShortcut_Add_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change shortcut &apos;{0}&apos; path.
        /// </summary>
        internal static string ShortcutsManager_ChangeShortcutPath_Change_shortcut_path {
            get {
                return ResourceManager.GetString("ShortcutsManager_ChangeShortcutPath_Change_shortcut_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy shortcut {0} path.
        /// </summary>
        internal static string ShortcutsManager_GetShortcutPath_Copy_shortcut_path {
            get {
                return ResourceManager.GetString("ShortcutsManager_GetShortcutPath_Copy_shortcut_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin initialized.
        /// </summary>
        internal static string ShortcutsManager_Init_Plugin_initialized {
            get {
                return ResourceManager.GetString("ShortcutsManager_Init_Plugin_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open shortcut &apos;{0}&apos;.
        /// </summary>
        internal static string ShortcutsManager_OpenShortcut_Open_shortcut {
            get {
                return ResourceManager.GetString("ShortcutsManager_OpenShortcut_Open_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove shortcut &apos;{0}&apos;.
        /// </summary>
        internal static string ShortcutsManager_RemoveShortcut_Remove_shortcut {
            get {
                return ResourceManager.GetString("ShortcutsManager_RemoveShortcut_Remove_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory or file does not exist! ({0}).
        /// </summary>
        internal static string Utils_OpenFileOrFolder_File_or_directory_does_not_exist {
            get {
                return ResourceManager.GetString("Utils_OpenFileOrFolder_File_or_directory_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist! ({0}).
        /// </summary>
        internal static string Utils_OpenFolder_Directory_does_not_exist {
            get {
                return ResourceManager.GetString("Utils_OpenFolder_Directory_does_not_exist", resourceCulture);
            }
        }
    }
}
